mod boss_registry;
mod bosses;
mod discipline;
mod effects;
mod flashpoint_bosses;
mod flashpoints;
mod lair_bosses;
mod pvp_instance;
mod raid_bosses;
mod raids;
mod shield_effects;

pub use boss_registry::{register_boss_npcs, clear_boss_registry, is_registered_boss};
pub use bosses::{lookup_boss, is_boss, get_boss_ids, lookup_area_content_type, BossInfo, ContentType, Difficulty};
pub use discipline::{Class, Discipline, Role};
pub use effects::*;
pub use flashpoints::{get_flashpoint_name, is_flashpoint, FLASHPOINT_AREAS};
pub use pvp_instance::is_pvp_area;
pub use raids::{get_operation_name, is_operation, is_world_boss, OPERATION_AREAS};
pub use shield_effects::SHIELD_EFFECT_IDS;
