//! Phase editing tab
//!
//! CRUD for boss phase definitions.
//! Uses PhaseDefinition DSL type directly.

use dioxus::prelude::*;

use crate::api;
use crate::types::{BossWithPath, Condition, EncounterItem, PhaseDefinition, Trigger};

use super::conditions::{ConditionsEditor, CounterConditionEditor};
use super::tabs::EncounterData;
use super::triggers::ComposableTriggerEditor;
use super::{DifficultiesEditor, InlineNameCreator};

// ─────────────────────────────────────────────────────────────────────────────
// Phases Tab
// ─────────────────────────────────────────────────────────────────────────────

/// Create a default phase definition
fn default_phase(name: String) -> PhaseDefinition {
    PhaseDefinition {
        id: String::new(), // Generated by backend
        name,
        enabled: true,
        display_text: None,
        start_trigger: Trigger::CombatStart,
        end_trigger: None,
        preceded_by: None,
        conditions: vec![],
        counter_condition: None,
        resets_counters: vec![],
        difficulties: vec![],
    }
}

#[component]
pub fn PhasesTab(
    boss_with_path: BossWithPath,
    encounter_data: EncounterData,
    expanded_phase: Signal<Option<String>>,
    hide_disabled_phases: Signal<bool>,
    on_change: EventHandler<Vec<PhaseDefinition>>,
    on_refetch: EventHandler<()>,
    on_status: EventHandler<(String, bool)>,
) -> Element {
    // Extract phases and badge IDs from BossWithPath
    let phases = boss_with_path.boss.phases.clone();
    let builtin_phase_ids = boss_with_path.builtin_phase_ids.clone();
    let modified_phase_ids = boss_with_path.modified_phase_ids.clone();

    let disabled_count = phases.iter().filter(|p| !p.enabled).count();

    // Filter phases based on toggle
    let visible_phases: Vec<PhaseDefinition> = if hide_disabled_phases() {
        phases.iter().filter(|p| p.enabled).cloned().collect()
    } else {
        phases.clone()
    };

    rsx! {
        div { class: "phases-tab",
            // Header
            div { class: "flex items-center justify-between mb-sm",
                div { class: "flex items-center gap-sm",
                    span { class: "text-sm text-secondary", "{phases.len()} phases" }
                    if disabled_count > 0 {
                        label { class: "flex items-center gap-xs text-xs text-muted cursor-pointer",
                            input {
                                r#type: "checkbox",
                                checked: hide_disabled_phases(),
                                onchange: move |e| hide_disabled_phases.set(e.checked()),
                            }
                            "Hide disabled ({disabled_count})"
                        }
                    }
                }
                {
                    let bwp = boss_with_path.clone();
                    let phases_for_create = phases.clone();
                    rsx! {
                        InlineNameCreator {
                            button_label: "+ New Phase",
                            placeholder: "Phase name...",
                            on_create: move |name: String| {
                                let phases_clone = phases_for_create.clone();
                                let boss_id = bwp.boss.id.clone();
                                let file_path = bwp.file_path.clone();
                                let phase = default_phase(name);
                                let item = EncounterItem::Phase(phase);
                                spawn(async move {
                                    match api::create_encounter_item(&boss_id, &file_path, &item).await {
                                        Ok(EncounterItem::Phase(created)) => {
                                            let created_id = created.id.clone();
                                            let mut current = phases_clone;
                                            current.push(created);
                                            on_change.call(current);
                                            expanded_phase.set(Some(created_id));
                                            on_status.call(("Created".to_string(), false));
                                        }
                                        Ok(_) => on_status.call(("Unexpected response type".to_string(), true)),
                                        Err(e) => on_status.call((e, true)),
                                    }
                                });
                            }
                        }
                    }
                }
            }

            // Phase list
            if visible_phases.is_empty() {
                if phases.is_empty() {
                    div { class: "empty-state text-sm", "No phases defined" }
                } else {
                    div { class: "empty-state text-sm", "All phases are disabled (toggle above to show)" }
                }
            } else {
                for phase in visible_phases {
                    {
                        let phase_key = phase.id.clone();
                        let is_expanded = expanded_phase() == Some(phase_key.clone());
                        let phases_for_row = phases.clone();
                        let phase_is_builtin = builtin_phase_ids.contains(&phase.id);
                        let phase_is_modified = modified_phase_ids.contains(&phase.id);

                        rsx! {
                            PhaseRow {
                                key: "{phase_key}",
                                phase: phase.clone(),
                                all_phases: phases_for_row,
                                is_builtin: phase_is_builtin,
                                is_modified: phase_is_modified,
                                boss_with_path: boss_with_path.clone(),
                                expanded: is_expanded,
                                encounter_data: encounter_data.clone(),
                                on_toggle: move |_| {
                                    expanded_phase.set(if is_expanded { None } else { Some(phase_key.clone()) });
                                },
                                on_change: on_change,
                                on_refetch: on_refetch,
                                on_status: on_status,
                                on_collapse: move |_| expanded_phase.set(None),
                            }
                        }
                    }
                }
            }
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Phase Row
// ─────────────────────────────────────────────────────────────────────────────

#[component]
fn PhaseRow(
    phase: PhaseDefinition,
    all_phases: Vec<PhaseDefinition>,
    is_builtin: bool,
    is_modified: bool,
    boss_with_path: BossWithPath,
    expanded: bool,
    encounter_data: EncounterData,
    on_toggle: EventHandler<()>,
    on_change: EventHandler<Vec<PhaseDefinition>>,
    on_refetch: EventHandler<()>,
    on_status: EventHandler<(String, bool)>,
    on_collapse: EventHandler<()>,
) -> Element {
    let mut is_dirty = use_signal(|| false);
    let trigger_label = phase.start_trigger.label();

    rsx! {
        div { class: if phase.enabled { "list-item" } else { "list-item item-disabled" },
            // Header row
            div {
                class: "list-item-header",
                onclick: move |_| on_toggle.call(()),

                // Expand arrow
                span { class: "list-item-expand", if expanded { "▼" } else { "▶" } }

                // Origin indicator (B)uilt-in / (M)odified / (C)ustom
                if is_builtin {
                    span {
                        class: "timer-origin timer-origin-builtin",
                        title: "Built-in: ships with the app",
                        "B"
                    }
                } else if is_modified {
                    span {
                        class: "timer-origin timer-origin-modified",
                        title: "Modified: built-in phase you have edited",
                        "M"
                    }
                } else {
                    span {
                        class: "timer-origin timer-origin-custom",
                        title: "Custom: created by you",
                        "C"
                    }
                }

                span { class: "font-medium", "{phase.name}" }
                if expanded && is_dirty() {
                    span { class: "unsaved-indicator", title: "Unsaved changes" }
                }
                span { class: "text-xs text-mono text-muted", "{phase.id}" }
                span { class: "tag", "{trigger_label}" }
            }

            // Expanded content
            if expanded {
                {
                    let all_phases_for_save = all_phases.clone();
                    let all_phases_for_delete = all_phases.clone();
                    let bwp_for_save = boss_with_path.clone();
                    let bwp_for_delete = boss_with_path.clone();
                    let is_reset = is_builtin || is_modified;
                    rsx! {
                        div { class: "list-item-body",
                            PhaseEditForm {
                                phase: phase.clone(),
                                all_phases: all_phases,
                                is_builtin: is_builtin,
                                is_modified: is_modified,
                                encounter_data: encounter_data,
                                on_dirty: move |dirty: bool| is_dirty.set(dirty),
                                on_save: move |updated: PhaseDefinition| {
                                    // Update parent state synchronously so props refresh and dirty indicator clears
                                    let mut current = all_phases_for_save.clone();
                                    if let Some(idx) = current.iter().position(|p| p.id == updated.id) {
                                        current[idx] = updated.clone();
                                        on_change.call(current);
                                    }
                                    on_status.call(("Saving...".to_string(), false));
                                    let boss_id = bwp_for_save.boss.id.clone();
                                    let file_path = bwp_for_save.file_path.clone();
                                    let item = EncounterItem::Phase(updated);
                                    spawn(async move {
                                        match api::update_encounter_item(&boss_id, &file_path, &item, None).await {
                                            Ok(_) => {
                                                on_status.call(("Saved".to_string(), false));
                                                on_refetch.call(());
                                            }
                                            Err(_) => on_status.call(("Failed to save".to_string(), true)),
                                        }
                                    });
                                },
                                on_delete: {
                                    let all_phases = all_phases_for_delete.clone();
                                    move |phase_to_delete: PhaseDefinition| {
                                        let all_phases = all_phases.clone();
                                        let boss_id = bwp_for_delete.boss.id.clone();
                                        let file_path = bwp_for_delete.file_path.clone();
                                        spawn(async move {
                                            match api::delete_encounter_item("phase", &phase_to_delete.id, &boss_id, &file_path).await {
                                                Ok(_) => {
                                                    if is_reset {
                                                        on_status.call(("Reset to built-in".to_string(), false));
                                                        on_collapse.call(());
                                                        on_refetch.call(());
                                                    } else {
                                                        let updated: Vec<_> = all_phases.iter()
                                                            .filter(|p| p.id != phase_to_delete.id)
                                                            .cloned()
                                                            .collect();
                                                        on_change.call(updated);
                                                        on_collapse.call(());
                                                        on_status.call(("Deleted".to_string(), false));
                                                    }
                                                }
                                                Err(err) => {
                                                    on_status.call((err, true));
                                                }
                                            }
                                        });
                                    }
                                },
                            }
                        }
                    }
                }
            }
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Phase Edit Form
// ─────────────────────────────────────────────────────────────────────────────

#[component]
fn PhaseEditForm(
    phase: PhaseDefinition,
    all_phases: Vec<PhaseDefinition>,
    #[props(default)] is_builtin: bool,
    #[props(default)] is_modified: bool,
    encounter_data: EncounterData,
    on_save: EventHandler<PhaseDefinition>,
    on_delete: EventHandler<PhaseDefinition>,
    #[props(default)] on_dirty: EventHandler<bool>,
) -> Element {
    // Clone values needed for closures and display
    let phase_id_display = phase.id.clone();
    let phase_for_delete = phase.clone();
    let phase_for_draft = phase.clone();
    let original = phase.clone();

    let mut draft = use_signal(|| phase_for_draft);
    let mut just_saved = use_signal(|| false);
    let mut confirm_delete = use_signal(|| false);

    // Reset just_saved when user makes new changes after saving
    let original_for_effect = original.clone();
    use_effect(move || {
        if draft() != original_for_effect && just_saved() {
            just_saved.set(false);
        }
    });

    let has_changes = use_memo(move || !just_saved() && draft() != original);

    // Notify parent when dirty state changes
    use_effect(move || {
        on_dirty.call(has_changes());
    });

    // Get phase IDs for preceded_by dropdown (exclude self)
    let phase_ids: Vec<String> = all_phases
        .iter()
        .filter(|p| p.id != phase_id_display)
        .map(|p| p.id.clone())
        .collect();

    let handle_save = move |_| {
        just_saved.set(true);
        let updated = draft();
        on_save.call(updated);
    };

    let handle_delete = move |_| {
        on_delete.call(phase_for_delete.clone());
    };

    rsx! {
        div { class: "phase-edit-form",
            div { class: "encounter-item-grid",
                // ═══ LEFT: Identity Card ═════════════════════════════════════
                div { class: "form-card",
                    div { class: "form-card-header",
                        i { class: "fa-solid fa-tag" }
                        span { "Identity" }
                    }
                    div { class: "form-card-content",
                        div { class: "form-row-hz",
                            label { "Phase ID" }
                            code { class: "tag-muted text-mono text-xs", "{phase_id_display}" }
                        }

                        div { class: "form-row-hz",
                            label { "Name" }
                            input {
                                class: "input-inline",
                                style: "width: 200px;",
                                value: "{draft().name}",
                                oninput: move |e| {
                                    let mut d = draft();
                                    d.name = e.value();
                                    draft.set(d);
                                }
                            }
                        }

                        div { class: "form-row-hz",
                            label { "Display Text" }
                            input {
                                class: "input-inline",
                                style: "width: 200px;",
                                placeholder: "(defaults to name)",
                                value: "{draft().display_text.clone().unwrap_or_default()}",
                                oninput: move |e| {
                                    let mut d = draft();
                                    d.display_text = if e.value().is_empty() { None } else { Some(e.value()) };
                                    draft.set(d);
                                }
                            }
                        }

                        div { class: "form-row-hz",
                            label { class: "flex items-center",
                                "Difficulties"
                                span {
                                    class: "help-icon",
                                    title: "Only activate this phase on selected difficulties. Empty = all difficulties.",
                                    "?"
                                }
                            }
                            DifficultiesEditor {
                                difficulties: draft().difficulties.clone(),
                                on_change: move |updated: Vec<String>| {
                                    let mut d = draft();
                                    d.difficulties = updated;
                                    draft.set(d);
                                }
                            }
                        }

                        // ─── Conditions subsection ─────────────────────────────
                        span { class: "text-sm font-bold text-secondary mt-sm", "Conditions" }

                        div { class: "form-row-hz mt-xs",
                            label { class: "flex items-center",
                                "Preceded By"
                                span {
                                    class: "help-icon",
                                    title: "This phase can only start if the specified phase was the most recent active phase",
                                    "?"
                                }
                            }
                            {
                                let selected_phase = draft().preceded_by.clone().unwrap_or_default();
                                rsx! {
                                    select {
                                        class: "select",
                                        style: "width: 180px;",
                                        onchange: move |e| {
                                            let mut d = draft();
                                            d.preceded_by = if e.value().is_empty() { None } else { Some(e.value()) };
                                            draft.set(d);
                                        },
                                        option { value: "", selected: selected_phase.is_empty(), "(none)" }
                                        for phase_id in &phase_ids {
                                            option {
                                                value: "{phase_id}",
                                                selected: phase_id == &selected_phase,
                                                "{phase_id}"
                                            }
                                        }
                                    }
                                }
                            }
                        }

                        div { class: "form-row-hz", style: "align-items: flex-start;",
                            label { class: "flex items-center", style: "padding-top: 6px;",
                                "Conditions"
                                span {
                                    class: "help-icon",
                                    title: "State conditions that must ALL be true for this phase to activate",
                                    "?"
                                }
                            }
                            ConditionsEditor {
                                conditions: draft().conditions.clone(),
                                encounter_data: encounter_data.clone(),
                                on_change: move |c| {
                                    let mut d = draft();
                                    d.conditions = c;
                                    draft.set(d);
                                }
                            }
                        }

                        // Legacy counter condition: show migration banner if old field has value
                        if draft().counter_condition.is_some() {
                            div { class: "legacy-conditions-banner",
                                i { class: "fa-solid fa-circle-info" }
                                span { "Legacy counter condition detected." }
                                button {
                                    class: "btn btn-sm",
                                    title: "Move legacy counter condition into the new Conditions system",
                                    onclick: move |_| {
                                        let mut d = draft();
                                        if let Some(cc) = d.counter_condition.take() {
                                            d.conditions.push(Condition::CounterCompare {
                                                counter_id: cc.counter_id,
                                                operator: cc.operator,
                                                value: cc.value,
                                            });
                                        }
                                        draft.set(d);
                                    },
                                    "Migrate"
                                }
                            }

                            div { class: "form-row-hz",
                                label { class: "flex items-center text-tertiary",
                                    "Counter (legacy)"
                                }
                                CounterConditionEditor {
                                    condition: draft().counter_condition.clone(),
                                    counters: encounter_data.counter_ids(),
                                    on_change: move |cond| {
                                        let mut d = draft();
                                        d.counter_condition = cond;
                                        draft.set(d);
                                    }
                                }
                            }
                        }

                        div { class: "form-row-hz", style: "align-items: flex-start;",
                            label { class: "flex items-center", style: "padding-top: 6px;",
                                "Resets"
                                span {
                                    class: "help-icon",
                                    title: "Counters to reset when this phase starts",
                                    "?"
                                }
                            }
                            CounterListEditor {
                                counters: draft().resets_counters.clone(),
                                available_counters: encounter_data.counter_ids(),
                                on_change: move |counters| {
                                    let mut d = draft();
                                    d.resets_counters = counters;
                                    draft.set(d);
                                }
                            }
                        }
                    }
                }

                // ═══ RIGHT: Trigger Card (2-column: Start / End) ═════════════
                div { class: "form-card",
                    div { class: "form-card-header",
                        i { class: "fa-solid fa-bolt" }
                        span { "Trigger" }
                    }
                    div { class: "form-card-content",
                        div { class: "trigger-two-col",
                            // ─── Start Trigger (left) ──────────────────────
                            div {
                                span { class: "text-sm font-bold text-secondary", "Start On" }
                                div { style: "margin-top: 6px;",
                                    ComposableTriggerEditor {
                                        trigger: draft().start_trigger,
                                        encounter_data: encounter_data.clone(),
                                        on_change: move |t| {
                                            let mut d = draft();
                                            d.start_trigger = t;
                                            draft.set(d);
                                        },
                                        hide_timer_only: true,
                                    }
                                }
                            }

                            // ─── End Trigger (right) ───────────────────────
                            div {
                                span { class: "text-sm font-bold text-secondary", "End On" }
                                div { style: "margin-top: 6px;",
                                    if let Some(end) = draft().end_trigger.clone() {
                                        div { class: "flex-col gap-xs",
                                            ComposableTriggerEditor {
                                                trigger: end,
                                                encounter_data: encounter_data.clone(),
                                                on_change: move |t| {
                                                    let mut d = draft();
                                                    d.end_trigger = Some(t);
                                                    draft.set(d);
                                                },
                                                hide_timer_only: true,
                                            }
                                            button {
                                                class: "btn btn-sm",
                                                style: "width: fit-content;",
                                                onclick: move |_| {
                                                    let mut d = draft();
                                                    d.end_trigger = None;
                                                    draft.set(d);
                                                },
                                                "Remove End Trigger"
                                            }
                                        }
                                    } else {
                                        div { class: "flex-col gap-xs",
                                            span { class: "text-muted text-sm", "(ends when another phase starts)" }
                                            button {
                                                class: "btn btn-sm",
                                                onclick: move |_| {
                                                    let mut d = draft();
                                                    d.end_trigger = Some(Trigger::CombatStart);
                                                    draft.set(d);
                                                },
                                                "+ Add End Trigger"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }

            // ─── Advanced Card ───────────────────────────────────────
            div { class: "form-card",
                div { class: "form-card-header",
                    i { class: "fa-solid fa-triangle-exclamation" }
                    span { "Advanced" }
                }
                div { class: "form-card-content",
                    label { class: "flex items-center gap-xs text-sm",
                        input {
                            r#type: "checkbox",
                            checked: draft().enabled,
                            onchange: move |e| {
                                let mut d = draft();
                                d.enabled = e.checked();
                                draft.set(d);
                            }
                        }
                        "Phase Enabled"
                    }
                    if !draft().enabled {
                        div { class: "text-xs text-warning mt-xs",
                            i { class: "fa-solid fa-triangle-exclamation" }
                            " Disabling a phase may break timers or other phases that depend on it."
                        }
                    }
                }
            }

            // ─── Actions ─────────────────────────────────────────────────────
            div { class: "form-actions",
                button {
                    class: if has_changes() { "btn btn-success btn-sm" } else { "btn btn-sm" },
                    disabled: !has_changes(),
                    onclick: handle_save,
                    "Save"
                }

                // Reset/Delete logic:
                // - Built-in unmodified: no delete button
                // - Modified built-in: "Reset to Built-in"
                // - Custom: "Delete" with confirmation
                if is_builtin {
                    // Pure built-in, unmodified — no action needed
                } else if is_modified {
                    if confirm_delete() {
                        span { class: "flex items-center gap-xs ml-auto",
                            "Reset to built-in?"
                            button {
                                class: "btn btn-warning btn-sm",
                                onclick: handle_delete,
                                "Yes"
                            }
                            button {
                                class: "btn btn-sm",
                                onclick: move |_| confirm_delete.set(false),
                                "No"
                            }
                        }
                    } else {
                        button {
                            class: "btn btn-warning btn-sm ml-auto",
                            onclick: move |_| confirm_delete.set(true),
                            "Reset to Built-in"
                        }
                    }
                } else {
                    if confirm_delete() {
                        span { class: "flex items-center gap-xs ml-auto",
                            "Delete?"
                            button {
                                class: "btn btn-danger btn-sm",
                                onclick: handle_delete,
                                "Yes"
                            }
                            button {
                                class: "btn btn-sm",
                                onclick: move |_| confirm_delete.set(false),
                                "No"
                            }
                        }
                    } else {
                        button {
                            class: "btn btn-danger btn-sm ml-auto",
                            onclick: move |_| confirm_delete.set(true),
                            "Delete"
                        }
                    }
                }
            }
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Counter List Editor (for resets_counters)
// ─────────────────────────────────────────────────────────────────────────────

#[component]
fn CounterListEditor(
    counters: Vec<String>,
    available_counters: Vec<String>,
    on_change: EventHandler<Vec<String>>,
) -> Element {
    let mut selected_counter = use_signal(String::new);

    // Filter available counters to exclude already selected ones
    let remaining: Vec<_> = available_counters
        .iter()
        .filter(|c| !counters.contains(c))
        .cloned()
        .collect();

    let counters_for_add = counters.clone();

    rsx! {
        div { class: "flex-col gap-xs",
            // Counter chips
            div { class: "flex flex-wrap gap-xs",
                for (idx, counter) in counters.iter().enumerate() {
                    {
                        let counters_clone = counters.clone();
                        rsx! {
                            span { class: "chip",
                                "{counter}"
                                button {
                                    class: "chip-remove",
                                    onclick: move |_| {
                                        let mut new_counters = counters_clone.clone();
                                        new_counters.remove(idx);
                                        on_change.call(new_counters);
                                    },
                                    "×"
                                }
                            }
                        }
                    }
                }
            }

            // Add from dropdown
            if !remaining.is_empty() {
                div { class: "flex gap-xs",
                    {
                        let current_selection = selected_counter();
                        rsx! {
                            select {
                                class: "select",
                                style: "width: 150px;",
                                onchange: move |e| selected_counter.set(e.value()),
                                option { value: "", selected: current_selection.is_empty(), "Select counter..." }
                                for counter_id in &remaining {
                                    option {
                                        value: "{counter_id}",
                                        selected: counter_id == &current_selection,
                                        "{counter_id}"
                                    }
                                }
                            }
                        }
                    }
                    button {
                        class: "btn btn-sm",
                        disabled: selected_counter().is_empty(),
                        onclick: move |_| {
                            let val = selected_counter();
                            if !val.is_empty() && !counters_for_add.contains(&val) {
                                let mut new_counters = counters_for_add.clone();
                                new_counters.push(val);
                                on_change.call(new_counters);
                                selected_counter.set(String::new());
                            }
                        },
                        "Add"
                    }
                }
            } else if available_counters.is_empty() {
                span { class: "text-xs text-muted", "No counters defined" }
            }
        }
    }
}
